groups:
  - name: mediashar.rules
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: |
          (
            rate(http_requests_total{status_code=~"5.."}[5m]) /
            rate(http_requests_total[5m])
          ) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected for {{ $labels.service }}"
          description: "Service {{ $labels.service }} has error rate above 5% for more than 5 minutes"

      # High response time
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High response time for {{ $labels.service }}"
          description: "95th percentile response time for {{ $labels.service }} is above 2 seconds"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: memory_usage_bytes > 500000000  # 500MB
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage for {{ $labels.service }}"
          description: "Memory usage for {{ $labels.service }} is above 500MB"

      # Database connection issues
      - alert: DatabaseConnectionFailure
        expr: |
          rate(db_queries_total{status="error"}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Database connection issues for {{ $labels.service }}"
          description: "Service {{ $labels.service }} is experiencing database connection failures"

      # High database query time
      - alert: SlowDatabaseQueries
        expr: |
          histogram_quantile(0.95, rate(db_query_duration_seconds_bucket[5m])) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries for {{ $labels.service }}"
          description: "95th percentile database query time for {{ $labels.service }} is above 1 second"

      # Too many goroutines
      - alert: HighGoRoutines
        expr: go_routines > 1000
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High number of goroutines for {{ $labels.service }}"
          description: "Service {{ $labels.service }} has more than 1000 goroutines"

      # gRPC high error rate
      - alert: GRPCHighErrorRate
        expr: |
          (
            rate(grpc_requests_total{status!="OK"}[5m]) /
            rate(grpc_requests_total[5m])
          ) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High gRPC error rate for {{ $labels.service }}"
          description: "gRPC error rate for {{ $labels.service }} is above 5%"

      # Payment failures
      - alert: PaymentFailures
        expr: |
          rate(payments_processed_total{status="failed"}[10m]) > 0.02
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is above 2% over the last 10 minutes"

      # Donation processing issues
      - alert: DonationProcessingIssues
        expr: |
          rate(donations_total{status="failed"}[10m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Donation processing issues"
          description: "Donation failure rate is above 10% over the last 10 minutes" 