global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MediaShar API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # MediaShar Microservices
  - job_name: 'donation-service'
    static_configs:
      - targets: ['donation-service:8091']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8092']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8093']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'currency-service'
    static_configs:
      - targets: ['currency-service:8084']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'language-service'
    static_configs:
      - targets: ['language-service:8085']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  # Database monitoring (via node exporter or postgres exporter)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Remote write configuration (optional)
# remote_write:
#   - url: "http://remote-prometheus-server/api/v1/write" 