// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/donation.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_CANCELLED   PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_COMPLETED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_CANCELLED",
		5: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_COMPLETED":   2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_CANCELLED":   4,
		"PAYMENT_STATUS_REFUNDED":    5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_donation_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_donation_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{0}
}

type PaymentProvider int32

const (
	PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED PaymentProvider = 0
	PaymentProvider_PAYMENT_PROVIDER_MIDTRANS    PaymentProvider = 1
	PaymentProvider_PAYMENT_PROVIDER_PAYPAL      PaymentProvider = 2
	PaymentProvider_PAYMENT_PROVIDER_STRIPE      PaymentProvider = 3
	PaymentProvider_PAYMENT_PROVIDER_QRIS        PaymentProvider = 4
	PaymentProvider_PAYMENT_PROVIDER_CRYPTO      PaymentProvider = 5
)

// Enum value maps for PaymentProvider.
var (
	PaymentProvider_name = map[int32]string{
		0: "PAYMENT_PROVIDER_UNSPECIFIED",
		1: "PAYMENT_PROVIDER_MIDTRANS",
		2: "PAYMENT_PROVIDER_PAYPAL",
		3: "PAYMENT_PROVIDER_STRIPE",
		4: "PAYMENT_PROVIDER_QRIS",
		5: "PAYMENT_PROVIDER_CRYPTO",
	}
	PaymentProvider_value = map[string]int32{
		"PAYMENT_PROVIDER_UNSPECIFIED": 0,
		"PAYMENT_PROVIDER_MIDTRANS":    1,
		"PAYMENT_PROVIDER_PAYPAL":      2,
		"PAYMENT_PROVIDER_STRIPE":      3,
		"PAYMENT_PROVIDER_QRIS":        4,
		"PAYMENT_PROVIDER_CRYPTO":      5,
	}
)

func (x PaymentProvider) Enum() *PaymentProvider {
	p := new(PaymentProvider)
	*p = x
	return p
}

func (x PaymentProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_donation_proto_enumTypes[1].Descriptor()
}

func (PaymentProvider) Type() protoreflect.EnumType {
	return &file_proto_donation_proto_enumTypes[1]
}

func (x PaymentProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentProvider.Descriptor instead.
func (PaymentProvider) EnumDescriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED        EventType = 0
	EventType_EVENT_TYPE_DONATION_CREATED   EventType = 1
	EventType_EVENT_TYPE_DONATION_COMPLETED EventType = 2
	EventType_EVENT_TYPE_DONATION_FAILED    EventType = 3
	EventType_EVENT_TYPE_PAYMENT_VERIFIED   EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_DONATION_CREATED",
		2: "EVENT_TYPE_DONATION_COMPLETED",
		3: "EVENT_TYPE_DONATION_FAILED",
		4: "EVENT_TYPE_PAYMENT_VERIFIED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":        0,
		"EVENT_TYPE_DONATION_CREATED":   1,
		"EVENT_TYPE_DONATION_COMPLETED": 2,
		"EVENT_TYPE_DONATION_FAILED":    3,
		"EVENT_TYPE_PAYMENT_VERIFIED":   4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_donation_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_donation_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{2}
}

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED       NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_DONATION_RECEIVED NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_PAYMENT_COMPLETED NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_PAYMENT_FAILED    NotificationType = 3
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_DONATION_RECEIVED",
		2: "NOTIFICATION_TYPE_PAYMENT_COMPLETED",
		3: "NOTIFICATION_TYPE_PAYMENT_FAILED",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":       0,
		"NOTIFICATION_TYPE_DONATION_RECEIVED": 1,
		"NOTIFICATION_TYPE_PAYMENT_COMPLETED": 2,
		"NOTIFICATION_TYPE_PAYMENT_FAILED":    3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_donation_proto_enumTypes[3].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_proto_donation_proto_enumTypes[3]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{3}
}

// Messages
type CreateDonationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	StreamerId    uint32                 `protobuf:"varint,4,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"`
	DonatorId     uint32                 `protobuf:"varint,5,opt,name=donator_id,json=donatorId,proto3" json:"donator_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsAnonymous   bool                   `protobuf:"varint,7,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDonationRequest) Reset() {
	*x = CreateDonationRequest{}
	mi := &file_proto_donation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDonationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDonationRequest) ProtoMessage() {}

func (x *CreateDonationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDonationRequest.ProtoReflect.Descriptor instead.
func (*CreateDonationRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDonationRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateDonationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateDonationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateDonationRequest) GetStreamerId() uint32 {
	if x != nil {
		return x.StreamerId
	}
	return 0
}

func (x *CreateDonationRequest) GetDonatorId() uint32 {
	if x != nil {
		return x.DonatorId
	}
	return 0
}

func (x *CreateDonationRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateDonationRequest) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *CreateDonationRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreateDonationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DonationId    uint32                 `protobuf:"varint,1,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,3,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	QrCodeBase64  string                 `protobuf:"bytes,4,opt,name=qr_code_base64,json=qrCodeBase64,proto3" json:"qr_code_base64,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDonationResponse) Reset() {
	*x = CreateDonationResponse{}
	mi := &file_proto_donation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDonationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDonationResponse) ProtoMessage() {}

func (x *CreateDonationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDonationResponse.ProtoReflect.Descriptor instead.
func (*CreateDonationResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDonationResponse) GetDonationId() uint32 {
	if x != nil {
		return x.DonationId
	}
	return 0
}

func (x *CreateDonationResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateDonationResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreateDonationResponse) GetQrCodeBase64() string {
	if x != nil {
		return x.QrCodeBase64
	}
	return ""
}

func (x *CreateDonationResponse) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetDonationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DonationId    uint32                 `protobuf:"varint,1,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationRequest) Reset() {
	*x = GetDonationRequest{}
	mi := &file_proto_donation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationRequest) ProtoMessage() {}

func (x *GetDonationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationRequest.ProtoReflect.Descriptor instead.
func (*GetDonationRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{2}
}

func (x *GetDonationRequest) GetDonationId() uint32 {
	if x != nil {
		return x.DonationId
	}
	return 0
}

type GetDonationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Donation      *Donation              `protobuf:"bytes,1,opt,name=donation,proto3" json:"donation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationResponse) Reset() {
	*x = GetDonationResponse{}
	mi := &file_proto_donation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationResponse) ProtoMessage() {}

func (x *GetDonationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationResponse.ProtoReflect.Descriptor instead.
func (*GetDonationResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{3}
}

func (x *GetDonationResponse) GetDonation() *Donation {
	if x != nil {
		return x.Donation
	}
	return nil
}

type GetDonationsByStreamerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamerId    uint32                 `protobuf:"varint,1,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationsByStreamerRequest) Reset() {
	*x = GetDonationsByStreamerRequest{}
	mi := &file_proto_donation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationsByStreamerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationsByStreamerRequest) ProtoMessage() {}

func (x *GetDonationsByStreamerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationsByStreamerRequest.ProtoReflect.Descriptor instead.
func (*GetDonationsByStreamerRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{4}
}

func (x *GetDonationsByStreamerRequest) GetStreamerId() uint32 {
	if x != nil {
		return x.StreamerId
	}
	return 0
}

func (x *GetDonationsByStreamerRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDonationsByStreamerRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetDonationsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Donations     []*Donation            `protobuf:"bytes,1,rep,name=donations,proto3" json:"donations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationsListResponse) Reset() {
	*x = GetDonationsListResponse{}
	mi := &file_proto_donation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationsListResponse) ProtoMessage() {}

func (x *GetDonationsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationsListResponse.ProtoReflect.Descriptor instead.
func (*GetDonationsListResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{5}
}

func (x *GetDonationsListResponse) GetDonations() []*Donation {
	if x != nil {
		return x.Donations
	}
	return nil
}

func (x *GetDonationsListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetDonationsListResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetDonationsListResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type UpdateDonationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DonationId    uint32                 `protobuf:"varint,1,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=donation.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDonationStatusRequest) Reset() {
	*x = UpdateDonationStatusRequest{}
	mi := &file_proto_donation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDonationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDonationStatusRequest) ProtoMessage() {}

func (x *UpdateDonationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDonationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDonationStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDonationStatusRequest) GetDonationId() uint32 {
	if x != nil {
		return x.DonationId
	}
	return 0
}

func (x *UpdateDonationStatusRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *UpdateDonationStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type UpdateDonationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDonationStatusResponse) Reset() {
	*x = UpdateDonationStatusResponse{}
	mi := &file_proto_donation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDonationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDonationStatusResponse) ProtoMessage() {}

func (x *UpdateDonationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDonationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDonationStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDonationStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDonationStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DonationId    uint32                 `protobuf:"varint,1,opt,name=donation_id,json=donationId,proto3" json:"donation_id,omitempty"`
	Provider      PaymentProvider        `protobuf:"varint,2,opt,name=provider,proto3,enum=donation.PaymentProvider" json:"provider,omitempty"`
	PaymentData   map[string]string      `protobuf:"bytes,3,rep,name=payment_data,json=paymentData,proto3" json:"payment_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_proto_donation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessPaymentRequest) GetDonationId() uint32 {
	if x != nil {
		return x.DonationId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetProvider() PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED
}

func (x *ProcessPaymentRequest) GetPaymentData() map[string]string {
	if x != nil {
		return x.PaymentData
	}
	return nil
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	QrCode        string                 `protobuf:"bytes,3,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=donation.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_proto_donation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *ProcessPaymentResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *ProcessPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type VerifyPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Provider      PaymentProvider        `protobuf:"varint,2,opt,name=provider,proto3,enum=donation.PaymentProvider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentRequest) Reset() {
	*x = VerifyPaymentRequest{}
	mi := &file_proto_donation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentRequest) ProtoMessage() {}

func (x *VerifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyPaymentRequest) GetProvider() PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED
}

type VerifyPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsVerified    bool                   `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=donation.PaymentStatus" json:"status,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentResponse) Reset() {
	*x = VerifyPaymentResponse{}
	mi := &file_proto_donation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentResponse) ProtoMessage() {}

func (x *VerifyPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentResponse.ProtoReflect.Descriptor instead.
func (*VerifyPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyPaymentResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *VerifyPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *VerifyPaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type HandleWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      PaymentProvider        `protobuf:"varint,1,opt,name=provider,proto3,enum=donation.PaymentProvider" json:"provider,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleWebhookRequest) Reset() {
	*x = HandleWebhookRequest{}
	mi := &file_proto_donation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleWebhookRequest) ProtoMessage() {}

func (x *HandleWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{12}
}

func (x *HandleWebhookRequest) GetProvider() PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED
}

func (x *HandleWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HandleWebhookRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HandleWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleWebhookResponse) Reset() {
	*x = HandleWebhookResponse{}
	mi := &file_proto_donation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleWebhookResponse) ProtoMessage() {}

func (x *HandleWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandleWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{13}
}

func (x *HandleWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleWebhookResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *HandleWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamDonationEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamerId    uint32                 `protobuf:"varint,1,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDonationEventsRequest) Reset() {
	*x = StreamDonationEventsRequest{}
	mi := &file_proto_donation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDonationEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDonationEventsRequest) ProtoMessage() {}

func (x *StreamDonationEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDonationEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamDonationEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{14}
}

func (x *StreamDonationEventsRequest) GetStreamerId() uint32 {
	if x != nil {
		return x.StreamerId
	}
	return 0
}

type DonationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=donation.EventType" json:"type,omitempty"`
	Donation      *Donation              `protobuf:"bytes,2,opt,name=donation,proto3" json:"donation,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationEvent) Reset() {
	*x = DonationEvent{}
	mi := &file_proto_donation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationEvent) ProtoMessage() {}

func (x *DonationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationEvent.ProtoReflect.Descriptor instead.
func (*DonationEvent) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{15}
}

func (x *DonationEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *DonationEvent) GetDonation() *Donation {
	if x != nil {
		return x.Donation
	}
	return nil
}

func (x *DonationEvent) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DonationEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=donation.NotificationType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_proto_donation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{16}
}

func (x *SendNotificationRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNotificationRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_proto_donation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{17}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventTypes    []EventType            `protobuf:"varint,2,rep,packed,name=event_types,json=eventTypes,proto3,enum=donation.EventType" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_donation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeEventsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeEventsRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type GetDonationStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamerId    uint32                 `protobuf:"varint,1,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"`
	StartDate     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDonationStatsRequest) Reset() {
	*x = GetDonationStatsRequest{}
	mi := &file_proto_donation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationStatsRequest) ProtoMessage() {}

func (x *GetDonationStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDonationStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{19}
}

func (x *GetDonationStatsRequest) GetStreamerId() uint32 {
	if x != nil {
		return x.StreamerId
	}
	return 0
}

func (x *GetDonationStatsRequest) GetStartDate() *timestamp.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetDonationStatsRequest) GetEndDate() *timestamp.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetDonationStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount    float64                `protobuf:"fixed64,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TotalDonations int32                  `protobuf:"varint,2,opt,name=total_donations,json=totalDonations,proto3" json:"total_donations,omitempty"`
	AverageAmount  float64                `protobuf:"fixed64,3,opt,name=average_amount,json=averageAmount,proto3" json:"average_amount,omitempty"`
	DailyStats     []*DonationStat        `protobuf:"bytes,4,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDonationStatsResponse) Reset() {
	*x = GetDonationStatsResponse{}
	mi := &file_proto_donation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDonationStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonationStatsResponse) ProtoMessage() {}

func (x *GetDonationStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonationStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDonationStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{20}
}

func (x *GetDonationStatsResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetDonationStatsResponse) GetTotalDonations() int32 {
	if x != nil {
		return x.TotalDonations
	}
	return 0
}

func (x *GetDonationStatsResponse) GetAverageAmount() float64 {
	if x != nil {
		return x.AverageAmount
	}
	return 0
}

func (x *GetDonationStatsResponse) GetDailyStats() []*DonationStat {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

type DonationStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationStat) Reset() {
	*x = DonationStat{}
	mi := &file_proto_donation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationStat) ProtoMessage() {}

func (x *DonationStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationStat.ProtoReflect.Descriptor instead.
func (*DonationStat) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{21}
}

func (x *DonationStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DonationStat) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DonationStat) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Data models
type Donation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount          float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StreamerId      uint32                 `protobuf:"varint,5,opt,name=streamer_id,json=streamerId,proto3" json:"streamer_id,omitempty"`
	DonatorId       uint32                 `protobuf:"varint,6,opt,name=donator_id,json=donatorId,proto3" json:"donator_id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsAnonymous     bool                   `protobuf:"varint,8,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	Status          PaymentStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=donation.PaymentStatus" json:"status,omitempty"`
	PaymentProvider PaymentProvider        `protobuf:"varint,10,opt,name=payment_provider,json=paymentProvider,proto3,enum=donation.PaymentProvider" json:"payment_provider,omitempty"`
	TransactionId   string                 `protobuf:"bytes,11,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt       *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PaymentTime     *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=payment_time,json=paymentTime,proto3" json:"payment_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Donation) Reset() {
	*x = Donation{}
	mi := &file_proto_donation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Donation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Donation) ProtoMessage() {}

func (x *Donation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Donation.ProtoReflect.Descriptor instead.
func (*Donation) Descriptor() ([]byte, []int) {
	return file_proto_donation_proto_rawDescGZIP(), []int{22}
}

func (x *Donation) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Donation) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Donation) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Donation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Donation) GetStreamerId() uint32 {
	if x != nil {
		return x.StreamerId
	}
	return 0
}

func (x *Donation) GetDonatorId() uint32 {
	if x != nil {
		return x.DonatorId
	}
	return 0
}

func (x *Donation) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Donation) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *Donation) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Donation) GetPaymentProvider() PaymentProvider {
	if x != nil {
		return x.PaymentProvider
	}
	return PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED
}

func (x *Donation) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Donation) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Donation) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Donation) GetPaymentTime() *timestamp.Timestamp {
	if x != nil {
		return x.PaymentTime
	}
	return nil
}

var File_proto_donation_proto protoreflect.FileDescriptor

const file_proto_donation_proto_rawDesc = "" +
	"\n" +
	"\x14proto/donation.proto\x12\bdonation\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\x15CreateDonationRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vstreamer_id\x18\x04 \x01(\rR\n" +
	"streamerId\x12\x1d\n" +
	"\n" +
	"donator_id\x18\x05 \x01(\rR\tdonatorId\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12!\n" +
	"\fis_anonymous\x18\a \x01(\bR\visAnonymous\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\"\xe2\x01\n" +
	"\x16CreateDonationResponse\x12\x1f\n" +
	"\vdonation_id\x18\x01 \x01(\rR\n" +
	"donationId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vpayment_url\x18\x03 \x01(\tR\n" +
	"paymentUrl\x12$\n" +
	"\x0eqr_code_base64\x18\x04 \x01(\tR\fqrCodeBase64\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"5\n" +
	"\x12GetDonationRequest\x12\x1f\n" +
	"\vdonation_id\x18\x01 \x01(\rR\n" +
	"donationId\"E\n" +
	"\x13GetDonationResponse\x12.\n" +
	"\bdonation\x18\x01 \x01(\v2\x12.donation.DonationR\bdonation\"q\n" +
	"\x1dGetDonationsByStreamerRequest\x12\x1f\n" +
	"\vstreamer_id\x18\x01 \x01(\rR\n" +
	"streamerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xb1\x01\n" +
	"\x18GetDonationsListResponse\x120\n" +
	"\tdonations\x18\x01 \x03(\v2\x12.donation.DonationR\tdonations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\x96\x01\n" +
	"\x1bUpdateDonationStatusRequest\x12\x1f\n" +
	"\vdonation_id\x18\x01 \x01(\rR\n" +
	"donationId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.donation.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"R\n" +
	"\x1cUpdateDonationStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x02\n" +
	"\x15ProcessPaymentRequest\x12\x1f\n" +
	"\vdonation_id\x18\x01 \x01(\rR\n" +
	"donationId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.donation.PaymentProviderR\bprovider\x12S\n" +
	"\fpayment_data\x18\x03 \x03(\v20.donation.ProcessPaymentRequest.PaymentDataEntryR\vpaymentData\x1a>\n" +
	"\x10PaymentDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x16ProcessPaymentResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\x12\x17\n" +
	"\aqr_code\x18\x03 \x01(\tR\x06qrCode\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.donation.PaymentStatusR\x06status\"t\n" +
	"\x14VerifyPaymentRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.donation.PaymentProviderR\bprovider\"\x81\x01\n" +
	"\x15VerifyPaymentResponse\x12\x1f\n" +
	"\vis_verified\x18\x01 \x01(\bR\n" +
	"isVerified\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.donation.PaymentStatusR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\xea\x01\n" +
	"\x14HandleWebhookRequest\x125\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x19.donation.PaymentProviderR\bprovider\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.donation.HandleWebhookRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x15HandleWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\">\n" +
	"\x1bStreamDonationEventsRequest\x12\x1f\n" +
	"\vstreamer_id\x18\x01 \x01(\rR\n" +
	"streamerId\"\xa2\x02\n" +
	"\rDonationEvent\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.donation.EventTypeR\x04type\x12.\n" +
	"\bdonation\x18\x02 \x01(\v2\x12.donation.DonationR\bdonation\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.donation.DonationEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.donation.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12?\n" +
	"\x04data\x18\x05 \x03(\v2+.donation.SendNotificationRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"g\n" +
	"\x16SubscribeEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x124\n" +
	"\vevent_types\x18\x02 \x03(\x0e2\x13.donation.EventTypeR\n" +
	"eventTypes\"\xac\x01\n" +
	"\x17GetDonationStatsRequest\x12\x1f\n" +
	"\vstreamer_id\x18\x01 \x01(\rR\n" +
	"streamerId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xc6\x01\n" +
	"\x18GetDonationStatsResponse\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x01R\vtotalAmount\x12'\n" +
	"\x0ftotal_donations\x18\x02 \x01(\x05R\x0etotalDonations\x12%\n" +
	"\x0eaverage_amount\x18\x03 \x01(\x01R\raverageAmount\x127\n" +
	"\vdaily_stats\x18\x04 \x03(\v2\x16.donation.DonationStatR\n" +
	"dailyStats\"P\n" +
	"\fDonationStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xc1\x04\n" +
	"\bDonation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vstreamer_id\x18\x05 \x01(\rR\n" +
	"streamerId\x12\x1d\n" +
	"\n" +
	"donator_id\x18\x06 \x01(\rR\tdonatorId\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x12!\n" +
	"\fis_anonymous\x18\b \x01(\bR\visAnonymous\x12/\n" +
	"\x06status\x18\t \x01(\x0e2\x17.donation.PaymentStatusR\x06status\x12D\n" +
	"\x10payment_provider\x18\n" +
	" \x01(\x0e2\x19.donation.PaymentProviderR\x0fpaymentProvider\x12%\n" +
	"\x0etransaction_id\x18\v \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fpayment_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vpaymentTime*\xbf\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x05*\xc4\x01\n" +
	"\x0fPaymentProvider\x12 \n" +
	"\x1cPAYMENT_PROVIDER_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PAYMENT_PROVIDER_MIDTRANS\x10\x01\x12\x1b\n" +
	"\x17PAYMENT_PROVIDER_PAYPAL\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_PROVIDER_STRIPE\x10\x03\x12\x19\n" +
	"\x15PAYMENT_PROVIDER_QRIS\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_PROVIDER_CRYPTO\x10\x05*\xac\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bEVENT_TYPE_DONATION_CREATED\x10\x01\x12!\n" +
	"\x1dEVENT_TYPE_DONATION_COMPLETED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_DONATION_FAILED\x10\x03\x12\x1f\n" +
	"\x1bEVENT_TYPE_PAYMENT_VERIFIED\x10\x04*\xad\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#NOTIFICATION_TYPE_DONATION_RECEIVED\x10\x01\x12'\n" +
	"#NOTIFICATION_TYPE_PAYMENT_COMPLETED\x10\x02\x12$\n" +
	" NOTIFICATION_TYPE_PAYMENT_FAILED\x10\x032\xb5\x04\n" +
	"\x0fDonationService\x12S\n" +
	"\x0eCreateDonation\x12\x1f.donation.CreateDonationRequest\x1a .donation.CreateDonationResponse\x12J\n" +
	"\vGetDonation\x12\x1c.donation.GetDonationRequest\x1a\x1d.donation.GetDonationResponse\x12e\n" +
	"\x16GetDonationsByStreamer\x12'.donation.GetDonationsByStreamerRequest\x1a\".donation.GetDonationsListResponse\x12e\n" +
	"\x14UpdateDonationStatus\x12%.donation.UpdateDonationStatusRequest\x1a&.donation.UpdateDonationStatusResponse\x12X\n" +
	"\x14StreamDonationEvents\x12%.donation.StreamDonationEventsRequest\x1a\x17.donation.DonationEvent0\x01\x12Y\n" +
	"\x10GetDonationStats\x12!.donation.GetDonationStatsRequest\x1a\".donation.GetDonationStatsResponse2\x89\x02\n" +
	"\x0ePaymentService\x12S\n" +
	"\x0eProcessPayment\x12\x1f.donation.ProcessPaymentRequest\x1a .donation.ProcessPaymentResponse\x12P\n" +
	"\rVerifyPayment\x12\x1e.donation.VerifyPaymentRequest\x1a\x1f.donation.VerifyPaymentResponse\x12P\n" +
	"\rHandleWebhook\x12\x1e.donation.HandleWebhookRequest\x1a\x1f.donation.HandleWebhookResponse2\xd0\x01\n" +
	"\x13NotificationService\x12a\n" +
	"\x18SendDonationNotification\x12!.donation.SendNotificationRequest\x1a\".donation.SendNotificationResponse\x12V\n" +
	"\x17SubscribeDonationEvents\x12 .donation.SubscribeEventsRequest\x1a\x17.donation.DonationEvent0\x01B\"Z github.com/rzfd/mediashar/pkg/pbb\x06proto3"

var (
	file_proto_donation_proto_rawDescOnce sync.Once
	file_proto_donation_proto_rawDescData []byte
)

func file_proto_donation_proto_rawDescGZIP() []byte {
	file_proto_donation_proto_rawDescOnce.Do(func() {
		file_proto_donation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_donation_proto_rawDesc), len(file_proto_donation_proto_rawDesc)))
	})
	return file_proto_donation_proto_rawDescData
}

var file_proto_donation_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_donation_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_donation_proto_goTypes = []any{
	(PaymentStatus)(0),                    // 0: donation.PaymentStatus
	(PaymentProvider)(0),                  // 1: donation.PaymentProvider
	(EventType)(0),                        // 2: donation.EventType
	(NotificationType)(0),                 // 3: donation.NotificationType
	(*CreateDonationRequest)(nil),         // 4: donation.CreateDonationRequest
	(*CreateDonationResponse)(nil),        // 5: donation.CreateDonationResponse
	(*GetDonationRequest)(nil),            // 6: donation.GetDonationRequest
	(*GetDonationResponse)(nil),           // 7: donation.GetDonationResponse
	(*GetDonationsByStreamerRequest)(nil), // 8: donation.GetDonationsByStreamerRequest
	(*GetDonationsListResponse)(nil),      // 9: donation.GetDonationsListResponse
	(*UpdateDonationStatusRequest)(nil),   // 10: donation.UpdateDonationStatusRequest
	(*UpdateDonationStatusResponse)(nil),  // 11: donation.UpdateDonationStatusResponse
	(*ProcessPaymentRequest)(nil),         // 12: donation.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),        // 13: donation.ProcessPaymentResponse
	(*VerifyPaymentRequest)(nil),          // 14: donation.VerifyPaymentRequest
	(*VerifyPaymentResponse)(nil),         // 15: donation.VerifyPaymentResponse
	(*HandleWebhookRequest)(nil),          // 16: donation.HandleWebhookRequest
	(*HandleWebhookResponse)(nil),         // 17: donation.HandleWebhookResponse
	(*StreamDonationEventsRequest)(nil),   // 18: donation.StreamDonationEventsRequest
	(*DonationEvent)(nil),                 // 19: donation.DonationEvent
	(*SendNotificationRequest)(nil),       // 20: donation.SendNotificationRequest
	(*SendNotificationResponse)(nil),      // 21: donation.SendNotificationResponse
	(*SubscribeEventsRequest)(nil),        // 22: donation.SubscribeEventsRequest
	(*GetDonationStatsRequest)(nil),       // 23: donation.GetDonationStatsRequest
	(*GetDonationStatsResponse)(nil),      // 24: donation.GetDonationStatsResponse
	(*DonationStat)(nil),                  // 25: donation.DonationStat
	(*Donation)(nil),                      // 26: donation.Donation
	nil,                                   // 27: donation.ProcessPaymentRequest.PaymentDataEntry
	nil,                                   // 28: donation.HandleWebhookRequest.HeadersEntry
	nil,                                   // 29: donation.DonationEvent.MetadataEntry
	nil,                                   // 30: donation.SendNotificationRequest.DataEntry
	(*timestamp.Timestamp)(nil),           // 31: google.protobuf.Timestamp
}
var file_proto_donation_proto_depIdxs = []int32{
	31, // 0: donation.CreateDonationResponse.expires_at:type_name -> google.protobuf.Timestamp
	26, // 1: donation.GetDonationResponse.donation:type_name -> donation.Donation
	26, // 2: donation.GetDonationsListResponse.donations:type_name -> donation.Donation
	0,  // 3: donation.UpdateDonationStatusRequest.status:type_name -> donation.PaymentStatus
	1,  // 4: donation.ProcessPaymentRequest.provider:type_name -> donation.PaymentProvider
	27, // 5: donation.ProcessPaymentRequest.payment_data:type_name -> donation.ProcessPaymentRequest.PaymentDataEntry
	0,  // 6: donation.ProcessPaymentResponse.status:type_name -> donation.PaymentStatus
	1,  // 7: donation.VerifyPaymentRequest.provider:type_name -> donation.PaymentProvider
	0,  // 8: donation.VerifyPaymentResponse.status:type_name -> donation.PaymentStatus
	1,  // 9: donation.HandleWebhookRequest.provider:type_name -> donation.PaymentProvider
	28, // 10: donation.HandleWebhookRequest.headers:type_name -> donation.HandleWebhookRequest.HeadersEntry
	2,  // 11: donation.DonationEvent.type:type_name -> donation.EventType
	26, // 12: donation.DonationEvent.donation:type_name -> donation.Donation
	31, // 13: donation.DonationEvent.timestamp:type_name -> google.protobuf.Timestamp
	29, // 14: donation.DonationEvent.metadata:type_name -> donation.DonationEvent.MetadataEntry
	3,  // 15: donation.SendNotificationRequest.type:type_name -> donation.NotificationType
	30, // 16: donation.SendNotificationRequest.data:type_name -> donation.SendNotificationRequest.DataEntry
	2,  // 17: donation.SubscribeEventsRequest.event_types:type_name -> donation.EventType
	31, // 18: donation.GetDonationStatsRequest.start_date:type_name -> google.protobuf.Timestamp
	31, // 19: donation.GetDonationStatsRequest.end_date:type_name -> google.protobuf.Timestamp
	25, // 20: donation.GetDonationStatsResponse.daily_stats:type_name -> donation.DonationStat
	0,  // 21: donation.Donation.status:type_name -> donation.PaymentStatus
	1,  // 22: donation.Donation.payment_provider:type_name -> donation.PaymentProvider
	31, // 23: donation.Donation.created_at:type_name -> google.protobuf.Timestamp
	31, // 24: donation.Donation.updated_at:type_name -> google.protobuf.Timestamp
	31, // 25: donation.Donation.payment_time:type_name -> google.protobuf.Timestamp
	4,  // 26: donation.DonationService.CreateDonation:input_type -> donation.CreateDonationRequest
	6,  // 27: donation.DonationService.GetDonation:input_type -> donation.GetDonationRequest
	8,  // 28: donation.DonationService.GetDonationsByStreamer:input_type -> donation.GetDonationsByStreamerRequest
	10, // 29: donation.DonationService.UpdateDonationStatus:input_type -> donation.UpdateDonationStatusRequest
	18, // 30: donation.DonationService.StreamDonationEvents:input_type -> donation.StreamDonationEventsRequest
	23, // 31: donation.DonationService.GetDonationStats:input_type -> donation.GetDonationStatsRequest
	12, // 32: donation.PaymentService.ProcessPayment:input_type -> donation.ProcessPaymentRequest
	14, // 33: donation.PaymentService.VerifyPayment:input_type -> donation.VerifyPaymentRequest
	16, // 34: donation.PaymentService.HandleWebhook:input_type -> donation.HandleWebhookRequest
	20, // 35: donation.NotificationService.SendDonationNotification:input_type -> donation.SendNotificationRequest
	22, // 36: donation.NotificationService.SubscribeDonationEvents:input_type -> donation.SubscribeEventsRequest
	5,  // 37: donation.DonationService.CreateDonation:output_type -> donation.CreateDonationResponse
	7,  // 38: donation.DonationService.GetDonation:output_type -> donation.GetDonationResponse
	9,  // 39: donation.DonationService.GetDonationsByStreamer:output_type -> donation.GetDonationsListResponse
	11, // 40: donation.DonationService.UpdateDonationStatus:output_type -> donation.UpdateDonationStatusResponse
	19, // 41: donation.DonationService.StreamDonationEvents:output_type -> donation.DonationEvent
	24, // 42: donation.DonationService.GetDonationStats:output_type -> donation.GetDonationStatsResponse
	13, // 43: donation.PaymentService.ProcessPayment:output_type -> donation.ProcessPaymentResponse
	15, // 44: donation.PaymentService.VerifyPayment:output_type -> donation.VerifyPaymentResponse
	17, // 45: donation.PaymentService.HandleWebhook:output_type -> donation.HandleWebhookResponse
	21, // 46: donation.NotificationService.SendDonationNotification:output_type -> donation.SendNotificationResponse
	19, // 47: donation.NotificationService.SubscribeDonationEvents:output_type -> donation.DonationEvent
	37, // [37:48] is the sub-list for method output_type
	26, // [26:37] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_donation_proto_init() }
func file_proto_donation_proto_init() {
	if File_proto_donation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_donation_proto_rawDesc), len(file_proto_donation_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_donation_proto_goTypes,
		DependencyIndexes: file_proto_donation_proto_depIdxs,
		EnumInfos:         file_proto_donation_proto_enumTypes,
		MessageInfos:      file_proto_donation_proto_msgTypes,
	}.Build()
	File_proto_donation_proto = out.File
	file_proto_donation_proto_goTypes = nil
	file_proto_donation_proto_depIdxs = nil
}
